############################################################
# Dockerfile to build SQL Container Image
# based on Original mariadb Image
############################################################
# Container sql
############################################################

# Set the base Image
FROM mariadb:10.2.8

# File Author / Maintainer
MAINTAINER Sven Berger
