############################################################
# Dockerfile to build Syncthing Image
# based on Linuxserver Syncthing
############################################################
# Container syncthing
############################################################

# Set the base Image
#FROM linuxserver/syncthing:137
#FROM linuxserver/syncthing:137
#FROM linuxserver/syncthing:137
#FROM linuxserver/syncthing:137
#FROM linuxserver/syncthing:137
FROM linuxserver/syncthing:137

# File Author / Maintainer
MAINTAINER Sven Berger
