############################################################
# Dockerfile to build Syncthing Image
# based on Linuxserver Syncthing
############################################################
# Container syncthing
############################################################

# Set the base Image
#FROM collabora/code
FROM linuxserver/syncthing:134

# File Author / Maintainer
MAINTAINER Sven Berger
