############################################################
# Dockerfile to build collaboran code Image
# based on Original collabora/code
############################################################
# Container office
############################################################

# Set the base Image
#FROM collabora/code
FROM collabora/code:3.2.2.1
#FROM collabora/code:3.3.1.3

# File Author / Maintainer
MAINTAINER Sven Berger
