############################################################
# Dockerfile to build collaboran code Image
# based on Original collabora/code
############################################################
# Container office
############################################################

# Set the base Image
#FROM collabora/code:3.2.2.1
#FROM collabora/code:3.3.0.3
#FROM collabora/code:3.3.1.2
#FROM collabora/code:3.3.1.2
#FROM collabora/code:3.3.1.3
#FROM collabora/code:3.4.0.8
#FROM collabora/code:3.4.1.1
#FROM collabora/code:3.4.2.1
FROM collabora/code:4.0.0.2

# File Author / Maintainer
MAINTAINER Sven Berger