############################################################
# Dockerfile to build nginx for Nextcloud FPM Image
# based on Original nginx Image
############################################################
# Container web
############################################################

# Set the base Image
FROM nginx

# File Author / Maintainer
MAINTAINER Sven Berger

# Nginx Config hinzufügen
COPY scripte/nginx.conf /etc/nginx/nginx.conf
